### ISSUE TITLE
Add support for OAuth authentication

### ISSUE THREAD

**Issue by robstewart57** [haskell-github-trust/smtp-mail#20]
Hi @spencerjanssen,

Would you accept this pull request, which I submitted against the repository that previously maintained this library?

https://github.com/jhickner/smtp-mail/pull/38

This change adds `sendMailWithLoginOAuthSTARTTLS` to the `Network.Mail.SMTP` module.

**Comment by spencerjanssen** [comment]
Yes, that change is welcome. Would you please include in the PR:

- A version bump to 0.5.0.0 (due to the new constructor in `AuthType`)
- An entry in `CHANGELOG.md` for 0.5.0.0 describing your changes

If you happen to have any ideas on how to test OAuth in CI that would be cool too, but that isn't a blocker by any means.

Cheers!

**Comment by robstewart57** [comment]
Hi @spencerjanssen ,

I've created a pull request: https://github.com/haskell-github-trust/smtp-mail/pull/23

**Comment by spencerjanssen** [comment]
Completed in #23
